### PR TITLE
Update support for android-sdk-plugin to 1.4.x

### PR DESCRIPTION
**Pull request by pfn**

### CODE REVIEW

**Comment by dancingrobot84** [comment]
Hi! Thanks for the effort, but, I'm afraid, such change will break compatibility with earlier versions of android-sdk-plugin because `target-sdk-version` is still a SettingKey there. Could you fix it in a way that sbt-structure will read both SettingKey and TaskKey?

I would like to ask you to add a test for this change as well. There is `android` test project in `extractor/src/test/data/0.13` directory; you could use it as an example. Please note that android tests are not executed on Travis; it requires you to run them manually on your machine. However, I think that it is sufficient to run only android tests in case of your change. You can run them by executing `^ testOnly -- -ex "android"` command in SBT repl.

If you need any help, feel free to get in touch with me.

**Comment by pfn** [comment]
Updated with backward compat support for 1.3.x and a trivial test case that copies the 1.3.x test case. (Speaking of which, updating those structure.xml files sucks)

**Comment by dancingrobot84** [comment]
Great! Thank you.

**Comment by pfn** [comment]
@dancingrobot84 How do we use this locally in IDEA?

**Comment by dancingrobot84** [comment]
@pfn You need to package sbt-structure for SBT 0.13. You can do it by running `^^ 0.13 package` in `extractor` project in SBT repl. Then you need to replace `launcher/sbt-structure-0.13.jar` file in Scala plugin directory with the jar you've just built.

In a week or two, when changes awaiting review are accepted, the new version of sbt-structure will be released and used in Scala plugin.

**Comment by dancingrobot84** [comment]
sbt-structure has been updated in Scala plugin 1.9.0. You can use it with the latest IDEA 15 EAP

**Comment by pfn** [comment]
Are there plans to release a version for 14.1? I hope android-sdk-plugin
users aren't stuck until 15 is GA :(

--

**Comment by dancingrobot84** [comment]
@pfn As far as I know there is no plans for another release for IDEA 14 yet. We'll revise changes and if it would be not too much painful to adapt them to IDEA 14, we'll make a release.

**Comment by dancingrobot84** [comment]
@pfn Backported your changes to Scala plugin 1.5.4 for IDEA 14.1

**Comment by pfn** [comment]
That's awesome, thanks!

--

**Pull request merged**
