### PR TITLE
Use AndroidManifest.xml from processManifest (helps with minSdkVersion)

### PR DESCRIPTION
**Pull request by pfn**
The test cases have not been fully updated so that they have all of the new plugin's dependencies properly checked. It's rather painful to update as I'm on Windows and there are numerous errors that occur which are spurious, and it's hard to tell what needs to be fixed.

### CODE REVIEW

**Comment by pfn** [comment]
Related issue which this helps to address https://youtrack.jetbrains.com/issue/IDEA-149924

**Comment by pfn** [comment]
ping @dancingrobot84

**Comment by dancingrobot84** [comment]
@pfn Sorry, I am unable to merge your changes, since I'm not a JB employee anymore. Hope @pavelfatin or @Alefas will take a look at them soon.

**Comment by pfn** [comment]
@dancingrobot84 I'm disappointed to hear you're not working at jetbrains anymore, good luck with wherever you are working next.

**Comment by dancingrobot84** [comment]
@pfn Thank you for the kind words!

**Comment by pfn** [comment]
ping @pavelfatin @Alefas 

Can I get some help with this?

**Comment by pfn** [comment]
I'm confused, has this been released? I'm running IntelliJ 2016.1 and it seems this has regressed?

**Comment by mutcianm** [comment]
Sorry for the delay, the updated sbt-structure dependency hasn't been bundled up until now.
You can check if it works in today's EAP build of Scala plugin.

**Pull request merged**
