### PR TITLE
Add support for sbt-android 1.6.0+

### PR DESCRIPTION
**Pull request by pfn**
retains support for all previous versions

Please merge/release asap @pavelfatin sbt-android users are unable to properly import sbt-android projects

Thank you!

### CODE REVIEW

**Comment by jastice** [comment]
Hi! Could you provide a link to any project where the import problem is fixed by this? Thanks!

**Comment by pfn** [comment]
https://github.com/pfn/qicr and https://github.com/pfn/keepshare are both
fixed by this

**Comment by soc** [comment]
```
[info] ImportSpec

[info] 

[info] Actual structure should

[info] + equal expected one in 'bare' project [0.13.7]

[info] + equal expected one in 'simple' project [0.13.7]

[info] + equal expected one in 'multiple' project [0.13.7]

[info] + equal expected one in 'dependency' project [0.13.7]

[info] + equal expected one in 'classifiers' project [0.13.7]

[info] + equal expected one in 'optional' project [0.13.7]

[error] ! equal expected one in 'play' project [0.13.7]

[error]     SAXParseException: Premature end of file. (ErrorHandlerWrapper.java:177)

[error] com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:198)

[error] com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)

[error] com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:441)

[error] com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:368)

[error] com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1436)

[error] com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:1019)

[error] com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)

[error] com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)

[error] com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)

[error] com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)

[error] com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)

[error] com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)

[error] com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:648)

[error] com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:332)

[info] o equal expected one in 'android-1.4' project [0.13.7]

[info] ANDROID_HOME is not defined

[info] o equal expected one in 'android' project [0.13.7]

[info] ANDROID_HOME is not defined

[info] + equal expected one in 'ide-settings' project [0.13.7]

[info] + equal expected one in 'sbt-idea' project [0.13.7]

[info] + equal expected one in 'custom-test-config' project [0.13.7]

[info]  

[info]  

[info] Total for specification ImportSpec

[info] Finished in 6 minutes 45 seconds, 738 ms

[info] 12 examples, 0 failure, 1 error, 2 skipped

[info] 

[error] Error: Total 24, Failed 0, Errors 1, Passed 21, Skipped 2

[error] Error during tests:

[error] 	org.jetbrains.sbt.ImportSpec

[error] (extractor/test:test) sbt.TestsFailedException: Tests unsuccessful

[error] Total time: 425 s, completed Jul 15, 2016 8:20:02 PM
```

**Comment by jastice** [comment]
@soc I've had this error on Travis, but unable to reproduce it locally, and it disappeared after making some innocuous commits. Does it happen for you on the `pfn-master` branch?

**Comment by pfn** [comment]
Travis isn't setup to run the android importing tests for sbt-structure

**Comment by jastice** [comment]
Yes, but this XML error happens on the `play` import test.

**Comment by soc** [comment]
@jastice No, I just copied the error from Travis into the PR so that it's easier to see what the issue is...

**Comment by jastice** [comment]
@soc Oh ok. Yeah, that issue is already fixed (and didn't have anything to do with this PR)

**Pull request merged**
